# Generated by Django 5.0.3 on 2024-03-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mldb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="movies",
            field=models.ManyToManyField(related_name="movie_genres", to="mldb.movie"),
        ),
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(related_name="movie_genres", to="mldb.genre"),
        ),
    ]
