# Generated by Django 5.0.3 on 2024-03-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mldb", "0002_genre_movies_movie_rating_alter_movie_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
