name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Consider moving these to a requirements-dev.txt or similar
        pip install black flake8 isort mypy pytest types-requests
    - name: Check code format with black
      run: |
        black --check --line-length 120 . 
    - name: Check import order with isort
      run: |
        isort --check-only --profile black .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude='venv/*'
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude='venv/*,*/__init__.py'
    - name: MyPy static tests
      run: |
        mypy . --ignore-missing-imports --exclude '^venv/'
    - name: Run Tests
      run: |
        DJANGO_TESTING=true python manage.py test
